model:
  name: "research_crew"

  version: "v0.1.18"

  authors:
    - "Your Name <you@example.com>"

  skills:
    - "Natural Language Understanding"
    - "Natural Language Generation"
    - "Information Retrieval and Synthesis"
    - "Fact Extraction"
    - "Knowledge Synthesis"

  locators:
    - type: "source-code"
      url: "https://github.com/agntcy/csit/tree/main/samples/crewai/simple_crew"

  extensions:
    - name: "oasf.agntcy.org/features/runtime/io-mapper"
      version: "v1.0.0"
      specs:
        input_name: "topic"
        input_type: "string"
        output_name: "report"
        output_type: "file"
        output_description: "A fully fledge reports with the mains topics, each with a full section of information. Formatted as markdown without '```'"
    - name: "oasf.agntcy.org/features/observability/logging"
      version: "v1.0.0"
      specs:
        type: "stdout"
        format: "<string>"
    - name: "oasf.agntcy.org/features/observability/metrics"
      version: "v1.0.0"
      specs:
        token_usage:
          - "total_tokens"
          - "prompt_tokens"
          - "cached_prompt_tokens"
          - "completion_tokens"
          - "successful_requests"
        task_duration: "task_duration"
    - name: "oasf.agntcy.org/features/framework/llm"
      version: "v1.0.0"
      specs:
        model: "ollama/llama3.1"
        base_url: "http://localhost:11434"
    - name: "oasf.agntcy.org/features/framework/evaluation"
      version: "v1.0.0"
      specs:
        provider: "local"
        type: "evaluator agent"
    - name: "oasf.agntcy.org/features/framework/orchestration"
      version: "v1.0.0"
      specs:
        type: "sequential"
    - name: "oasf.agntcy.org/features/framework/memory"
      version: "v1.0.0"
      specs:
        enabled: false

builder:
  source: "/simple_crew"
  source-ignore:
    - ".venv/"

  llmanalyzer: false
  crewai: true
  runtime: true
