# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

tasks:
  dependencies:
    internal: true
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  run:crew:
    desc: Run crew
    deps:
      - dependencies
    cmds:
      - poetry run python -m simple_crew.main

  run:test:
    desc: Run crew
    deps:
      - dependencies
    cmds:
      - poetry run python -m simple_crew.main test

  default:
    cmd: task -l