# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

tasks:
  dependencies:
    internal: true
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  run:test:
    desc: Run tests
    deps:
      - dependencies
    cmds:
      - poetry run python -m research.main

  default:
    cmd: task -l