model:
  name: "research"

  version: "0.1.0"

  authors:
    - "Zsolt Kacsándi <zkacsand@cisco.com>"

  skills:
    - "Natural Language Understanding"
    - "Natural Language Generation"
    - "Information Retrieval and Synthesis"
    - "Fact Extraction"
    - "Knowledge Synthesis"

  locators:
    - type: "source-code"
      url: "https://github.com/agntcy/csit/tree/main/samples/langgraph/research"

  extensions:
    - name: "oasf.agntcy.org/features/runtime/io-mapper"
      version: "v1.0.0"
      specs:
        input_name: "topic"
        input_type: "string"
        output_name: "report"
        output_type: "string"
        output_description: "Create a detailed markdown report about {state['topic']} based on these research findings: {'\n'.join(state['research_findings'])}. Expand each finding into a full section, ensuring comprehensive coverage."
    - name: "oasf.agntcy.org/features/observability/logging"
      version: "v1.0.0"
      specs:
        type: "stdout"
        format: "<string>"
    - name: "oasf.agntcy.org/features/framework/llm"
      version: "v1.0.0"
      specs:
        model: "gpt-4o-mini"
        timeout: null
        temperature: 0
        max_tokens: null
        max_retries: 2
    - name: "oasf.agntcy.org/features/framework/orchestration"
      version: "v1.0.0"
      specs:
        type: "graph"

builder:
  source: "/research"
  source-ignore:
    - ".venv/"

  llmanalyzer: false
  crewai: false
  runtime: true
