# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

tasks:
  setup:docker-env-cli-stdout:
    desc: Create env file
    internal: true
    status:
      - test -f .env
    cmds:
      - ../utils/setup-env.sh

  test:docker-env-cli-stdout:
    desc: Run docker image
    internal: true
    cmds:
      - docker run --env-file .env docker-env-cli-stdout "Hello, World"

  build:
    desc: Build images
    internal: true
    cmds:
      - docker buildx bake --load

  run:test:
    desc: Run test
    deps:
      - setup:docker-env-cli-stdout
      - build
    cmds:
      - task: test:docker-env-cli-stdout

  default:
    cmd: task -l