# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

tasks:
  dependencies:
    internal: true
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  run:crew:
    desc: Run application main
    deps:
      - dependencies
    cmds:
      - poetry run python -m model.crew

  run:test-deepeval:
    internal: true
    cmds:
      - poetry run python -m tests._deepeval

  run:test-ragas:
    internal: true
    cmds:
      - poetry run python -m tests._ragas

  run:test:
    deps:
      - dependencies
    cmds:
      - task: run:test-deepeval
      - task: run:test-ragas

  default:
    cmd: task -l