# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

includes:
  agents:
    taskfile: ./agents/docker-env-cli-stdout/Taskfile.yml
    dir: ./agents/docker-env-cli-stdout
    excludes: [default]
  autogen:
    taskfile: ./autogen/semantic-router/Taskfile.yml
    dir: ./autogen/semantic-router
    excludes: [default]
  crewai:
    taskfile: ./crewai/simple_crew/Taskfile.yml
    dir: ./crewai/simple_crew
    excludes: [default]
  evaluation:
    taskfile: ./evaluation/Taskfile.yml
    dir: ./evaluation
    excludes: [default]
  langgraph:
    taskfile: ./langgraph/research/Taskfile.yml
    dir: ./langgraph/research
    excludes: [default]
  llama-deploy:
    taskfile: ./llama-deploy/llama-sum/Taskfile.yml
    dir: ./llama-deploy/llama-sum
    excludes: [default]
  llama-index:
    taskfile: ./llama-index/research/Taskfile.yml
    dir: ./llama-index/research/
    excludes: [default]

tasks:
  run:test:all:
    - task: agents:run:test
    - task: autogen:run:test
    - task: crewai:run:test
    - task: evaluation:run:test
    - task: langgraph:run:test
    - task: llama-deploy:run:test
    - task: llama-index:run:test

  default:
    cmd: task -l