# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  lib:
    taskfile: ../Taskfile.yml
    flatten: true

tasks:
  run:test:
    desc: Run tests
    deps:
      - compose
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - poetry sync --no-root
      - poetry run pytest
