# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

tasks:
  dependencies:
    desc: Install dependencies
    internal: true
    cmds:
      - poetry sync --no-root

  lint:
    desc: Run lint with black
    deps:
      - dependencies
    cmds:
      - poetry run ruff check .

  lint-fix:
    desc: Run lint and autofix with black
    deps:
      - dependencies
    cmds:
      - poetry run ruff check --fix .

  compose:
    desc: 'Run docker-compose'
    internal: true
    cmds:
      - docker compose up --build -d

  kind:
    desc: 'Run app in kind'
    vars:
      PARENT_DIR:
        sh: basename ${PWD}
    cmds:
      - docker compose build
      - kind create cluster --name {{.PARENT_DIR}} || true
      - |
        # For each image
        images=($(yq '.services | keys | map("{{.PARENT_DIR}}-" + .) | join(" ")' docker-compose.yaml))
        kind load docker-image ${images[@]} --name {{.PARENT_DIR}}
      - kubectl --context kind-{{.PARENT_DIR}} apply -k .

  run:test:
    desc: Run tests
    deps:
      - compose
    cmds:
      - poetry sync --no-root
      - poetry run pytest

  default:
    cmd: task -l