# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

includes:
  gateway:
    taskfile: ./agntcy-agp/Taskfile.yml
    dir: ./agntcy-agp
    excludes: [default]

  directory:
    taskfile: ./agntcy-dir/Taskfile.yml
    dir: ./agntcy-dir
    excludes: [default]

tasks:
  default:
    cmd: task -l